constants:
  api:
    prefix: /api/auth
  enum:
    scan-package: com.green.common

server:
  port: ${AUTH_PORT}

spring:
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-jpa.yaml
      - optional:classpath:application-auth.yaml
      - optional:classpath:application-redis.yaml
      - optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/my_gu_auth?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useServerPrepStmts=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
    # [수신] Member 캐시 정보를 받기 위한 설정
    consumer:
      group-id: auth-service-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.green.common.model,com.green.common.kafka"
  mail:
    host: smtp.gmail.com        # Gmail SMTP 서버 주소
    port: 587                   # STARTTLS 방식의 표준 포트
    username: ${MAIL_USERNAME}  # 발송에 사용할 Gmail 주소
    password: ${MAIL_PASSWORD}  # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # SMTP 인증 사용 (필수)
          starttls:
            enable: true        # 보안 연결(TLS) 사용 (필수)
            required: true
          timeout: 5000

