constants:
  api:
    prefix: ""
  enum:
    scan-package: com.green.member

server:
  port: ${MEMBER_PORT}

spring:
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-jpa.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  application:
    name: member-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/my_gu_member?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
