server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/{segment}

          - id: member-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/member/**, /api/admin/member/**

          - id: core-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/majors/**, /api/lectures/**, /api/courses/**, /api/admin/courses/**, /api/tuitions/**, /api/admin/tuitions/**, /api/scholarships/**, /api/facilities/**, /api/admin/facilities/**, /api/attendances/**, /api/grades/**

          - id: academic-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/academic/**, /api/admin/academic/**, /api/announcements/**, /api/admin/announcements/**, /api/notifications/**, /api/schedules/**, /api/admin/schedules/**